name: brew_brother_cafe
description: "A modern Flutter cafe management app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  
  # State Management
  get: ^4.6.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  
  # Network & Storage
  http: ^1.2.2
  dio: ^5.8.0
  shared_preferences: ^2.3.2
  hive_flutter: ^1.1.0
  
  # Utils
  intl: ^0.19.0
  flutter_smart_dialog: ^4.9.8
  loading_animation_widget: ^1.2.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/app-images/
    - assets/banners/
